### ISSUE TITLE
Compiler error: "You can only implement an interface"

### ISSUE THREAD

**Issue by mehdadoo** [DelishusCake/Singleton#3]
Sorry, the solution didn't work out of the box for me.
Haxe Compiler 3.2.0 says:
 "You can only implement an interface"

class DBManager implements Singleton
{...}

compiled with:
-lib Singleton

Is there any custom setup I should do?!

**Comment by DelishusCake** [comment]
Sorry! The current release is broken, but I'm not able to fix it yet. Until I can, you can grab a working version from a previous commit here:

https://github.com/DelishusCake/Singleton/blob/d36908f675f896867987dcef8f25698e9847b2e5/Singleton.hx

In this version you need to extend Singleton, but otherwise the usage is identical.

**Comment by mehdadoo** [comment]
Thanks for the fast reply!

This build totally works:
https://github.com/DelishusCake/Singleton/blob/9aa1f69675762e91ba0ac9b1381050e0749e7395/Singleton.hx

Great!!!

**Comment by player-03** [comment]
mehdadoo, can you try [my implementation](https://github.com/player-03/Singleton) and see if you still get this error? Because I can't seem to reproduce the issue.

(Make sure you've commented DelishusCake's version when you test it.)
